#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import requests

import click

import listb.mrtools as mrtools

@click.group()
def cli():
    pass

@click.command('crawl',
               short_help='Prints the URL and all suceeding URLs.')
@click.option('--url',
              prompt='Please enter URL',
              help='URL pointing to MathSciNet search result')
def crawl(url):
    """ Prints the URL and all suceeding URLs.
    
    If the search result is split into 5 pages and the URL to page
    3 is passed then the URLs of pages 3, 4, and 5 are printed.
    """
    _, urls = mrtools.crawl(url)
    click.echo('\n'.join(urls))

@click.command('mrnumbers',
               short_help='Prints the MR-numbers of the entries')
@click.option('--url',
              prompt='Please enter URL',
              help='URL pointing to MathSciNet search result')
@click.option('--crawl/--no-crawl',
              default=False,
              help='Crawl page and return all MR-numbers')
@click.option('--yaml',
              help='path to yaml file for output')
def mrnumbers(url, crawl, yaml):
    if crawl:
        sites, _ = mrtools.crawl(url)
    else:
        req = requests.get(url)
        sites = [req.text]
    
    mmrn = [mrtools.msn_to_mrnumbers(s) for s in sites]
    mmrn = [n for sublist in mmrn for n in sublist]
    
    if yaml:
        mrtools.yaml_dump(mmrn, yaml)
    
    click.echo('\n'.join(mmrn))

cli.add_command(crawl)
cli.add_command(mrnumbers)

if __name__ == '__main__':
    cli()